### ISSUE TITLE
CSS issue (tags)

### ISSUE THREAD

**Issue by lifeart** [patocallaghan/ember-octane-realworld#32]
![image](https://user-images.githubusercontent.com/1360552/74768323-6a975d00-5299-11ea-9185-563e7b3c981d.png)

**Comment by patocallaghan** [comment]
Thanks for the issue @lifeart. So this is a problem with the supplied RealWorld CSS. You'll see the same problem in other apps too such as the Angular and React ones. Seeing as that's the case I'm not overly bothered with fixing it unless we do it upstream too.

**Comment by patocallaghan** [comment]
Closing this issue as we've now merged this code into Ember Realworld and I'm archiving this repo.
