### ISSUE TITLE
Model attribute transforms might not be needed

### ISSUE THREAD

**Issue by Windvis** [patocallaghan/ember-octane-realworld#34]
I noticed that all model attributes have a transform listed. AFAIK transforms should only be used if the response type isn't what you want. Is that the case here? If not, I would just remove the transforms.

https://github.com/patocallaghan/ember-octane-realworld/blob/bed0ae000f4ee62a525c24f2ecf6952fee7f53e9/app/models/article.js#L15

**Comment by patocallaghan** [comment]
Thanks @Windvis 🙌I've addressed this feedback and the `@tracked` comment from Discord in https://github.com/patocallaghan/ember-octane-realworld/pull/38
